# runtime-accel: 実行時カーブ設定 + custom Studio RPC
CONFIG_ZMK_RUNTIME_ACCEL=y
CONFIG_ZMK_RUNTIME_ACCEL_STUDIO_RPC=y
CONFIG_ZMK_CUSTOM_SETTINGS=y
CONFIG_ZMK_CUSTOM_SETTINGS_STUDIO_RPC=y
CONFIG_ZMK_STUDIO_RPC_RX_BUF_SIZE=192
CONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE=192
CONFIG_ZMK_STUDIO_RPC_CUSTOM_SUBSYSTEM_REQUEST_PAYLOAD_MAX_BYTES=128
CONFIG_ZMK_LOW_PRIORITY_THREAD_STACK_SIZE=2048

# custom-settingsのboot読み込みに必要
CONFIG_MAIN_STACK_SIZE=2048
